---
- hosts: all
  become: yes
  roles:
    - role: goss
      tags: [apply_goss]

    - role: docker
      tags: [apply_docker]

#    - role: template
#      tags: [apply_template]

- hosts: consul
  become: yes
  roles:
    - role: consulserver
      tags: [apply_consul]

- hosts: monitoror
  become: yes
  roles:
    - role: monitoror
      tags: [apply_monitoror]

- hosts: vigil
  become: yes
  roles:
    - role: vigil
      tags: [apply_vigil]

- hosts: cassandra
  become: yes
  roles:
    - role: cassandra
      tags: [apply_cassandra]

- hosts: elasticsearch
  become: yes
  roles:
    - role: elasticsearch
      tags: [apply_elasticsearch]

- hosts: kafka
  become: yes
  roles:
    - role: kafka
      tags: [apply_kafka]

- hosts: spark
  become: yes
  roles:
    - role: spark
      tags: [apply_spark]
