---
- hosts: all
  become: yes
  roles:
    - role: docker
      tags: [apply_docker]

    - role: cassandra
      tags: [apply_cassandra]
      when: ansible_hostname | regex_search("^cassandra")

    - role: elasticsearch
      tags: [apply_elasticsearch]
      when: ansible_hostname | regex_search("^elasticsearch")

    - role: kafka
      tags: [apply_kafka]
      when: ansible_hostname | regex_search("^kafka")

    - role: spark
      tags: [apply_spark]
      when: ansible_hostname | regex_search("^spark")

    - role: monitoror
      tags: [apply_monitoror]
      when: ansible_hostname | regex_search("^monitoror")
